package com.xiaoxu.service.model;

/**
 * @author xiaoxu
 */
public class ChattingRecordsModel{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_records.id
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_records.send_user_id
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    private Integer sendUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_records.rec_user_id
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    private Integer recUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_records.datetime
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    private String datetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_records.status
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_records.con_img
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    private String conImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_records.context
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_records.id
     *
     * @return the value of chatting_records.id
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_records.id
     *
     * @param id the value for chatting_records.id
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_records.send_user_id
     *
     * @return the value of chatting_records.send_user_id
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public Integer getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_records.send_user_id
     *
     * @param sendUserId the value for chatting_records.send_user_id
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_records.rec_user_id
     *
     * @return the value of chatting_records.rec_user_id
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public Integer getRecUserId() {
        return recUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_records.rec_user_id
     *
     * @param recUserId the value for chatting_records.rec_user_id
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public void setRecUserId(Integer recUserId) {
        this.recUserId = recUserId;
    }

    public String getDatetime() {
        return datetime;
    }

    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_records.status
     *
     * @return the value of chatting_records.status
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_records.status
     *
     * @param status the value for chatting_records.status
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_records.con_img
     *
     * @return the value of chatting_records.con_img
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public String getConImg() {
        return conImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_records.con_img
     *
     * @param conImg the value for chatting_records.con_img
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public void setConImg(String conImg) {
        this.conImg = conImg == null ? null : conImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_records.context
     *
     * @return the value of chatting_records.context
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_records.context
     *
     * @param context the value for chatting_records.context
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

}