package com.yangyang.dao;

import com.yangyang.dataobject.FollowedDao;

import java.util.List;

public interface FollowedDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_followed
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_followed
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    int insert(FollowedDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_followed
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    int insertSelective(FollowedDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_followed
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    FollowedDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_followed
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    int updateByPrimaryKeySelective(FollowedDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_followed
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    int updateByPrimaryKey(FollowedDao record);

    /**
     * 查询关注状态
     * @param loginUserId
     * @param itemUserId
     * @return
     */
    FollowedDao selectByUserIdAndItemUserId(Integer loginUserId, Integer itemUserId);

    /**
     * 取消收藏
     * @param userId
     * @param itemUserId
     */
    void cancelFollow(Integer userId, Integer itemUserId);

    /**
     * 查询关注人列表
     * @param userId
     * @return
     */
    List<FollowedDao> selectByUserId(Integer userId);

    /**
     * 查询粉丝列表
     * @param followedId
     * @return
     */
    List<FollowedDao> selectByFollowedId(Integer followedId);

    /**
     * 查询粉丝的ID
     * @param userId
     * @return
     */
    List<Integer> selectByUserIdAsList(Integer userId);
}