package com.xiaoxu.dao;

import com.xiaoxu.dataobject.ChattingRecordsDao;

import java.util.List;

public interface ChattingRecordsDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_records
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_records
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    int insert(ChattingRecordsDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_records
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    int insertSelective(ChattingRecordsDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_records
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    ChattingRecordsDao selectByPrimaryKey(Integer id);
    List<ChattingRecordsDao> getChattingRecords(Integer loginUserId, Integer recUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_records
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    int updateByPrimaryKeySelective(ChattingRecordsDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_records
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ChattingRecordsDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_records
     *
     * @mbg.generated Wed Jan 08 20:38:29 CST 2020
     */
    int updateByPrimaryKey(ChattingRecordsDao record);

  /*  *//**
     * 根据登陆用户查询最后一条未读消息
     * @param loginUserId
     * @return
     *//*
    ChattingRecordsDao selectByRecUserId(Integer loginUserId);

    *//**
     * 根据登陆用户ID查询未读消息总数
     * @param loginUserId
     * @return
     *//*
    Integer selectCountOfStatus(Integer loginUserId);*/

    List<ChattingRecordsDao> selectUnreadMessage(Integer loginUserId);
}