package com.xiaoxu.dao;

import com.xiaoxu.dataobject.FavouriteDao;

public interface FavouriteDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favourite
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favourite
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int insert(FavouriteDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favourite
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int insertSelective(FavouriteDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favourite
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    FavouriteDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favourite
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int updateByPrimaryKeySelective(FavouriteDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_favourite
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int updateByPrimaryKey(FavouriteDao record);

    /**
     * 根据登陆用户的ID和帖子ID查询数据
     * @param loginUserId
     * @param itemId
     * @return
     */
    FavouriteDao selectByUserIdAndItemId(Integer loginUserId, Integer itemId);

    /**
     * 取消收藏
     * @param userId
     * @param itemId
     */
    void cancelFavourite(Integer userId, Integer itemId);
}