package com.xiaoxu.dao;

import com.xiaoxu.dataobject.ItemDao;
import com.xiaoxu.dataobject.PageDao;

import java.util.List;

/**
 * @author xiaoxu
 */
public interface ItemDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int insert(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int insertSelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    ItemDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int updateByPrimaryKey(ItemDao record);

    /**
     * 根据搜索内容查询数量
     *
     * @param pageDao
     * @return
     */
    int selectCount(PageDao pageDao);

    /**
     * 将搜索内容、开始位置以及每页包含的数量组装成一个JavaBean，并根据此JavaBean获取当前页码的所有帖子
     *
     * @param pageDao
     * @return
     */
    List<ItemDao> getItemModeLForPage(PageDao pageDao);

    /**
     * 用户点赞后增加帖子点赞数
     *
     * @param id
     * @return
     */
    int increaseLike(Integer id);

    /**
     * 用户取消点赞后减少点赞数
     *
     * @param id
     * @return
     */
    int decreaseLike(Integer id);

    /**
     * 用户发表评论后增加评论数
     *
     * @param id
     * @return
     */
    int increaseComment(Integer id);

    /**
     * 用户删除评论后减少评论数
     *
     * @param id
     * @return
     */
    int decreaseComment(Integer id);

    /**
     * 用户收藏后增加收藏数
     *
     * @param id
     * @return
     */
    int increaseFavourite(Integer id);

    /**
     * 用户取消收藏后减少收藏数
     *
     * @param id
     * @return
     */
    int decreaseFavourite(Integer id);

    /**
     * 查询用户发布的帖子数量
     * @param pageDao
     * @return
     */
    int selectItemCount(PageDao pageDao);

    /**
     * 查询用户发布的帖子
     * @param pageDao
     * @return
     */
    List<ItemDao> getUserItemModeLForPage(PageDao pageDao);
}