package com.xiaoxu.dao;

import com.xiaoxu.dataobject.LikeDao;

/**
 * @author xiaoxu
 */
public interface LikeDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int insert(LikeDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int insertSelective(LikeDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    LikeDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int updateByPrimaryKeySelective(LikeDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    int updateByPrimaryKey(LikeDao record);

    /**
     * 根据登陆用户的ID和帖子ID查询数据
     * @param loginUserId
     * @param itemId
     * @return
     */
    LikeDao selectByUserIdAndItemId(Integer loginUserId, Integer itemId);

    /**
     * 点赞
     * @param userId
     * @param itemId
     */
    void doLike(Integer userId, Integer itemId);

    /**
     * 取消点赞
     * @param userId
     * @param itemId
     */
    void cancelLike(Integer userId, Integer itemId);
}