package com.xiaoxu.dataobject;

import java.util.Date;

/**
 * @author xiaoxu
 */
public class CommentDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.datetime
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Date datetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.user_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.item_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.context
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.id
     *
     * @return the value of user_comment.id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.id
     *
     * @param id the value for user_comment.id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.datetime
     *
     * @return the value of user_comment.datetime
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.datetime
     *
     * @param datetime the value for user_comment.datetime
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.user_id
     *
     * @return the value of user_comment.user_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.user_id
     *
     * @param userId the value for user_comment.user_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.item_id
     *
     * @return the value of user_comment.item_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.item_id
     *
     * @param itemId the value for user_comment.item_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.context
     *
     * @return the value of user_comment.context
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.context
     *
     * @param context the value for user_comment.context
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}