package com.xiaoxu.dataobject;

import java.util.Date;

/**
 * @author xiaoxu
 */
public class FollowedDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_followed.id
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_followed.user_id
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_followed.followed_id
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    private Integer followedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_followed.datetime
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    private Date datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_followed.id
     *
     * @return the value of user_followed.id
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_followed.id
     *
     * @param id the value for user_followed.id
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_followed.user_id
     *
     * @return the value of user_followed.user_id
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_followed.user_id
     *
     * @param userId the value for user_followed.user_id
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_followed.followed_id
     *
     * @return the value of user_followed.followed_id
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    public Integer getFollowedId() {
        return followedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_followed.followed_id
     *
     * @param followedId the value for user_followed.followed_id
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    public void setFollowedId(Integer followedId) {
        this.followedId = followedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_followed.datetime
     *
     * @return the value of user_followed.datetime
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_followed.datetime
     *
     * @param datetime the value for user_followed.datetime
     *
     * @mbg.generated Mon Dec 16 09:42:48 CST 2019
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
}