package com.yangyang.dataobject;

import java.util.Date;

/**
 * @author Administrator
 */
public class ItemDao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.con_img
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private String conImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.like
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer favourite;
    private Integer likes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.comment
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.user_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.context
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private String context;

    private Date datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.id
     *
     * @return the value of item_info.id
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.id
     *
     * @param id the value for item_info.id
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.con_img
     *
     * @return the value of item_info.con_img
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public String getConImg() {
        return conImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.con_img
     *
     * @param conImg the value for item_info.con_img
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setConImg(String conImg) {
        this.conImg = conImg == null ? null : conImg.trim();
    }

    public Integer getFavourite() {
        return favourite;
    }

    public void setFavourite(Integer favourite) {
        this.favourite = favourite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.like
     *
     * @return the value of item_info.like
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.like
     *
     * @param likes the value for item_info.like
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.comment
     *
     * @return the value of item_info.comment
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.comment
     *
     * @param comments the value for item_info.comment
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.user_id
     *
     * @return the value of item_info.user_id
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.user_id
     *
     * @param userId the value for item_info.user_id
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.context
     *
     * @return the value of item_info.context
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.context
     *
     * @param context the value for item_info.context
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    public Date getDatetime() {
        return datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
}