package com.yangyang.dataobject;

import java.util.Date;

/**
 * @author xiaoxu
 */
public class LikeDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_like.id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_like.user_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_like.item_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_like.datetime
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    private Date datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_like.id
     *
     * @return the value of user_like.id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_like.id
     *
     * @param id the value for user_like.id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_like.user_id
     *
     * @return the value of user_like.user_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_like.user_id
     *
     * @param userId the value for user_like.user_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_like.item_id
     *
     * @return the value of user_like.item_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_like.item_id
     *
     * @param itemId the value for user_like.item_id
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_like.datetime
     *
     * @return the value of user_like.datetime
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_like.datetime
     *
     * @param datetime the value for user_like.datetime
     *
     * @mbg.generated Tue Nov 26 14:48:06 CST 2019
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    @Override
    public String toString() {
        return "LikeDao{" +
                "id=" + id +
                ", userId=" + userId +
                ", itemId=" + itemId +
                ", datetime=" + datetime +
                '}';
    }
}